# Check that the "original_index" is consistent across all USPTO datasets

In [1]:
import pandas as pd

In [9]:
# Dataframes:
# uspto_no_trust_unfiltered
df1 = pd.read_parquet('/Users/danielwigh/projects_local/ORDerly_project/ORDerly/data/orderly/uspto_no_trust/unfiltered/unfiltered_orderly_ord.parquet')
# uspto_trust_filtered
df2 = pd.read_parquet('/Users/danielwigh/projects_local/ORDerly_project/ORDerly/data/orderly/uspto_with_trust/filtered/filtered_orderly_ord.parquet')
# uspto_with_trust_with_map
df3 = pd.read_parquet('/Users/danielwigh/projects_local/ORDerly_project/ORDerly/data/orderly/datasets_v5/orderly_with_trust_with_map_train.parquet')
# uspto_no_trust_no_map (ie orderly-benchmark)
df4 = pd.read_parquet('/Users/danielwigh/projects_local/ORDerly_project/ORDerly/data/orderly/datasets_v5/orderly_no_trust_no_map_train.parquet')

In [17]:
# find an "original_index" they all have in common
set(df1['original_index']).intersection(set(df2['original_index'])).intersection(set(df3['original_index'])).intersection(set(df4['original_index']))

{31,
 55,
 108,
 230,
 283,
 284,
 287,
 331,
 549,
 601,
 636,
 637,
 640,
 763,
 808,
 814,
 819,
 824,
 828,
 842,
 850,
 1126,
 1254,
 1265,
 1512,
 1660,
 1795,
 1797,
 1879,
 2035,
 2071,
 2115,
 2120,
 2671,
 3113,
 3335,
 3440,
 3445,
 3555,
 3996,
 4157,
 4251,
 4298,
 4384,
 4385,
 4761,
 4764,
 4928,
 4953,
 5012,
 5169,
 5173,
 5410,
 5419,
 5483,
 5575,
 5797,
 5822,
 5842,
 5881,
 5922,
 5952,
 5961,
 6010,
 6092,
 6106,
 6107,
 6111,
 6302,
 6322,
 6522,
 6523,
 6546,
 6562,
 6563,
 6677,
 6749,
 6892,
 6900,
 6905,
 7186,
 7252,
 7257,
 7266,
 7306,
 7331,
 7333,
 7341,
 7343,
 7344,
 7458,
 7491,
 7511,
 7606,
 7610,
 7618,
 7634,
 7642,
 7730,
 7749,
 7766,
 7771,
 7802,
 7881,
 7914,
 7917,
 8350,
 8445,
 8540,
 8557,
 8598,
 8651,
 8655,
 8671,
 9085,
 9154,
 9425,
 9547,
 9550,
 9553,
 9555,
 9560,
 9613,
 9745,
 9780,
 9833,
 10014,
 10024,
 10025,
 10030,
 10044,
 10054,
 10118,
 10127,
 10157,
 10420,
 10477,
 10769,
 10946,
 10999,
 11007,
 11017,
 11028,
 11031,
 11033,
 11034,
 11042,
 11046,
 11050,
 11061,
 11062,
 11100,
 11131,
 11134,
 11141,
 11146,
 11214,
 11220,
 11236,
 11242,
 11247,
 11255,
 11266,
 11329,
 11467,
 11481,
 11485,
 11488,
 11494,
 11497,
 11501,
 11753,
 12058,
 12092,
 12140,
 12215,
 12257,
 12284,
 12328,
 12362,
 12366,
 12367,
 12369,
 12444,
 12492,
 12507,
 12556,
 12564,
 12664,
 12839,
 12941,
 12961,
 13192,
 13216,
 13301,
 13504,
 13636,
 13638,
 13840,
 13843,
 13845,
 13848,
 13850,
 13855,
 13896,
 13915,
 13991,
 14260,
 14390,
 14493,
 14720,
 14725,
 14755,
 14847,
 14894,
 14983,
 15078,
 15145,
 15150,
 15178,
 15207,
 15373,
 15429,
 15447,
 15450,
 15497,
 15504,
 15529,
 15579,
 15622,
 15627,
 15676,
 15686,
 15749,
 15758,
 15764,
 15767,
 15783,
 15785,
 15812,
 15890,
 16007,
 16055,
 16068,
 16089,
 16424,
 16437,
 16675,
 16688,
 16760,
 16762,
 16763,
 17004,
 17035,
 17051,
 17067,
 17118,
 17202,
 17252,
 17262,
 17295,
 17319,
 17320,
 17744,
 18126,
 18264,
 18304,
 18310,
 18332,
 18403,
 18462,
 18480,
 18555,
 18669,
 18836,
 19065,
 19384,
 19395,
 19410,
 19434,
 19456,
 19598,
 19617,
 19657,
 19659,
 19675,
 19753,
 19837,
 19857,
 19864,
 20151,
 20198,
 20291,
 20406,
 20419,
 20450,
 20624,
 20852,
 20926,
 21123,
 21274,
 21283,
 21299,
 21303,
 21305,
 21316,
 21397,
 21407,
 21424,
 21470,
 21490,
 21515,
 21808,
 21820,
 21823,
 21852,
 22040,
 22052,
 22102,
 22111,
 22125,
 22330,
 22336,
 22343,
 22348,
 22350,
 22360,
 22364,
 22371,
 22379,
 22387,
 22518,
 22746,
 22751,
 22752,
 22753,
 22754,
 22755,
 22756,
 22757,
 22758,
 22759,
 22760,
 22762,
 22764,
 22765,
 22767,
 22769,
 22770,
 22772,
 22773,
 22776,
 22778,
 22780,
 22781,
 22785,
 22786,
 22787,
 22788,
 22789,
 22790,
 22792,
 22793,
 22795,
 22796,
 22801,
 22807,
 22808,
 22952,
 23139,
 23143,
 23207,
 23221,
 23251,
 23393,
 23397,
 23403,
 23406,
 23409,
 23445,
 23510,
 23524,
 23718,
 23834,
 23856,
 23960,
 24084,
 24179,
 24226,
 24232,
 24270,
 24279,
 24600,
 24653,
 24688,
 24692,
 24697,
 24746,
 24904,
 24939,
 24987,
 25154,
 25209,
 25211,
 25249,
 25361,
 25372,
 25376,
 25378,
 25382,
 25396,
 25399,
 25424,
 25442,
 25448,
 25456,
 25612,
 25648,
 25848,
 25876,
 25878,
 25893,
 25966,
 25970,
 25972,
 26283,
 26306,
 26455,
 26767,
 26780,
 26832,
 26837,
 27101,
 27190,
 27274,
 27292,
 27319,
 27476,
 27559,
 27588,
 27774,
 28049,
 28103,
 28163,
 28176,
 28247,
 28274,
 28279,
 28285,
 28292,
 28343,
 28366,
 28373,
 28730,
 28751,
 28756,
 28759,
 28879,
 28989,
 29003,
 29005,
 29030,
 29038,
 29041,
 29046,
 29048,
 29057,
 29073,
 29079,
 29084,
 29126,
 29145,
 29165,
 29188,
 29220,
 29337,
 29389,
 29415,
 29448,
 29601,
 29628,
 29776,
 29973,
 29987,
 30008,
 30125,
 30185,
 30330,
 30599,
 30676,
 30679,
 30680,
 30692,
 30735,
 30891,
 30914,
 30922,
 30926,
 30931,
 30934,
 30946,
 30949,
 30952,
 30960,
 30964,
 30967,
 30977,
 30980,
 30983,
 30990,
 30996,
 31008,
 31017,
 31035,
 31063,
 31100,
 31228,
 31229,
 31232,
 31248,
 31325,
 31406,
 31407,
 31409,
 31413,
 31417,
 31419,
 31423,
 31896,
 32177,
 32338,
 32359,
 32377,
 32439,
 32444,
 32543,
 32559,
 32577,
 32586,
 32677,
 32931,
 32940,
 32958,
 33046,
 33059,
 33061,
 33114,
 33118,
 33121,
 33123,
 33124,
 33221,
 33237,
 33607,
 33614,
 33628,
 33641,
 33656,
 33682,
 33685,
 33689,
 33696,
 33761,
 33762,
 33766,
 33843,
 33849,
 33905,
 34044,
 34055,
 34140,
 34408,
 34491,
 34608,
 34665,
 34702,
 34753,
 34966,
 34974,
 34979,
 35126,
 35129,
 35133,
 35157,
 35175,
 35414,
 35426,
 35567,
 35579,
 35606,
 35687,
 35950,
 36095,
 36106,
 36142,
 36204,
 36230,
 36243,
 36256,
 36274,
 36278,
 36306,
 36337,
 36408,
 36453,
 36454,
 36459,
 36607,
 36694,
 36722,
 36864,
 36897,
 37037,
 37039,
 37044,
 37046,
 37049,
 37051,
 37053,
 37056,
 37058,
 37064,
 37070,
 37170,
 37196,
 37200,
 37259,
 37264,
 37461,
 37468,
 37484,
 37496,
 37498,
 37504,
 37509,
 37522,
 37530,
 37586,
 37612,
 37638,
 37698,
 37824,
 37831,
 37879,
 38107,
 38124,
 38197,
 38338,
 38353,
 38388,
 38464,
 38513,
 38888,
 39036,
 39070,
 39077,
 39131,
 39136,
 39148,
 39161}

In [37]:
# check if a,b,c,d are all equal
index = 39077
a = df1[df1['original_index']==index]['rxn_str'].iloc[0]
b = df2[df2['original_index']==index]['rxn_str'].iloc[0]
c = df3[df3['original_index']==index]['rxn_str'].iloc[0]
d = df4[df4['original_index']==index]['rxn_str'].iloc[0]
a==b, a==c, a==d, b==c, b==d, c==d

(True, True, True, True, True, True)

# Find the rows in test set that are also in train

In [1]:
import pandas as pd

In [2]:
path = '/Users/dsw46/Projects_local/orderly_27_05/ORDerly/data/orderly/uspto_no_trust/filtered/filtered_orderly_ord.parquet'
df = pd.read_parquet(path)

In [3]:
solv = df[['solvent_000', 'solvent_001']]
#iterate over all rows
for index, row in solv.iterrows():
    if 'OCC1CCCO1' in row.values:
        print(index)
        print(row.values)
        break

34307
['OCC1CCCO1' None]

In [4]:
train_idx = range(int(len(df)*0.8))
test_idx = range(int(len(df)*0.8), len(df))
train_df = df.iloc[train_idx]
test_df = df.iloc[test_idx]

In [7]:
def get_intersection(df1, df2):
    return df1.index.intersection(df2.index)

,agent_000,agent_001,agent_002,date_of_experiment,extracted_from_file,grant_date,is_mapped,procedure_details,product_000,reactant_000,reactant_001,rxn_str,rxn_time,solvent_000,solvent_001,temperature,yield_000
545293,O=C([O-])[O-],[Cs+],None,NaT,ord_dataset-f8e6e6a2d2bf4135b9e346456c81700f,2014-01-01 00:04:00,True,To a solution of benzyl (3-hydroxy-4-methylphe...,Cc1ccc(NC(=O)OCc2ccccc2)cc1Oc1ccc([N+](=O)[O-]...,Cc1ccc(NC(=O)OCc2ccccc2)cc1O,O=[N+]([O-])c1ccc(Cl)nc1,[OH:1][C:2]1[CH:3]=[C:4]([NH:9][C:10](=[O:19])...,4.0,CCOC(C)=O,CN(C)C=O,25.0,75.4
545294,BrBr,[K+],None,NaT,ord_dataset-f8e6e6a2d2bf4135b9e346456c81700f,2014-01-01 00:04:00,True,To a solution of potassium thiocyanate (62.9 g...,Cc1ccc(NC(=O)OCc2ccccc2)cc1Oc1ccc2nc(N)sc2n1,Cc1ccc(NC(=O)OCc2ccccc2)cc1Oc1ccc(N)cn1,N#C[S-],[S-:1][C:2]#[N:3].[K+].[NH2:5][C:6]1[CH:7]=[CH...,18.0,CC(=O)O,None,25.0,73.5
545295,O=C([O-])[O-],[K+],None,NaT,ord_dataset-f8e6e6a2d2bf4135b9e346456c81700f,2014-01-01 00:04:00,True,"To a solution of benzyl {3-[(2-amino[1,3]thiaz...",Cc1ccc(NC(=O)OCc2ccccc2)cc1Oc1ccc2nc(NC(=O)C3C...,Cc1ccc(NC(=O)OCc2ccccc2)cc1Oc1ccc2nc(N)sc2n1,O=C(Cl)C1CC1,[NH2:1][C:2]1[S:3][C:4]2[C:9]([N:10]=1)=[CH:8]...,0.5,CO,c1ccncc1,25.0,81.4
545296,CN1CCC(C(=O)c2cccc(N)n2)CC1,O=C(Cl)c1c(F)cc(F)cc1F,None,NaT,ord_dataset-f8e6e6a2d2bf4135b9e346456c81700f,2014-01-01 00:04:00,True,The present invention is directed to a process...,CN1CCC(C(=O)C2CCCC(NC(=O)c3c(F)cc(F)cc3F)N2)CC1,CN1CCC(C(=O)c2cccc(NC(=O)c3c(F)cc(F)cc3F)n2)CC1,None,[F:1][C:2]1[CH:25]=[C:24]([F:26])[CH:23]=[C:22...,NaN,Clc1ccccc1,None,NaN,NaN
545297,Cl,None,None,NaT,ord_dataset-f8e6e6a2d2bf4135b9e346456c81700f,2014-01-01 00:04:00,True,To a suspension of {(cis)-1-acetyl-2-methyl-6-...,CC(=O)N1c2ccc(-c3ccc(CN4CCCCC4)cc3)cc2[C@H](N)...,CC(=O)N1c2ccc(-c3ccc(CN4CCCCC4)cc3)cc2[C@H](NC...,None,[C:1]([N:4]1[C:13]2[C:8](=[CH:9][C:10]([C:14]3...,NaN,CO,None,NaN,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
681612,C[O-],[Na+],None,NaT,ord_dataset-0b32b90cc77b4a3db47ad263e0bbc1a8,2016-01-01 00:09:00,True,10.0 g of p-acetoxystyrene was dissolved in 40...,C=Cc1ccc(O)cc1,C=Cc1ccc(OC(C)=O)cc1,None,C([O:4][C:5]1[CH:12]=[CH:11][C:8]([CH:9]=[CH2:...,5.0,CCOC(C)=O,CO,0.0,178.2
681613,C(=NC1CCCCC1)=NC1CCCCC1,CN(C)c1ccncc1,None,NaT,ord_dataset-0b32b90cc77b4a3db47ad263e0bbc1a8,2016-01-01 00:09:00,True,"4-(benzyloxy)benzoic acid (20.0 g, 87.6 mmol),...",CCCCCCOc1ccc(OC(=O)c2ccc(OCc3ccccc3)cc2)cc1,CCCCCCOc1ccc(O)cc1,O=C(O)c1ccc(OCc2ccccc2)cc1,[CH2:1]([O:8][C:9]1[CH:17]=[CH:16][C:12]([C:13...,3.0,ClCCl,O,25.0,70.3
681614,[Pd],None,None,NaT,ord_dataset-0b32b90cc77b4a3db47ad263e0bbc1a8,2016-01-01 00:09:00,True,The 4-(hexyloxy)phenyl 4-(benzyloxy)benzoate o...,CCCCCCOc1ccc(OC(=O)c2ccc(O)cc2)cc1,CCCCCCOc1ccc(OC(=O)c2ccc(OCc3ccccc3)cc2)cc1,None,C([O:8][C:9]1[CH:30]=[CH:29][C:12]([C:13]([O:1...,NaN,C1=CCC=CC1,C1CCOC1,60.0,NaN
681615,O=C([O-])O,[Na+],None,NaT,ord_dataset-0b32b90cc77b4a3db47ad263e0bbc1a8,2016-01-01 00:09:00,True,A 500 ml round bottom flask was charged with N...,COc1cccc(-c2nccn2-c2c(C(C)C)cc(Br)cc2C(C)C)c1,COc1cccc(C(=N)Nc2c(C(C)C)cc(Br)cc2C(C)C)c1,O=CCCl,[Br:1][C:2]1[CH:7]=[C:6]([CH:8]([CH3:10])[CH3:...,NaN,CC(C)O,O,NaN,78.6
681616,[Cu]I,CNC1CCCCC1NC,[Na+],NaT,ord_dataset-0b32b90cc77b4a3db47ad263e0bbc1a8,2016-01-01 00:09:00,True,A 100 ml three neck round bottom flask was cha...,Ic1ccc2c3ccccc3n(-c3ccccn3)c2c1,Brc1ccc2c3ccccc3n(-c3ccccn3)c2c1,[I-],Br[C:2]1[CH:14]=[CH:13][C:12]2[C:11]3[C:6](=[C...,NaN,C1COCCO1,O,NaN,83.1

# Find reactions in test set (rare-> other) that don't appear in train set

In [1]:
import pandas as pd

In [2]:
test_df_path = "/Users/dsw46/Library/CloudStorage/OneDrive-UniversityofCambridge/Datasets/orderly_v5/orderly_no_trust_no_map_test.parquet"
train_df_path = "/Users/dsw46/Library/CloudStorage/OneDrive-UniversityofCambridge/Datasets/orderly_v5/orderly_no_trust_with_map_train.parquet"
test_df = pd.read_parquet(test_df_path)
train_df = pd.read_parquet(train_df_path)

In [3]:

# Extract the values from the "rxn_str" column in train_df
train_rxn_str_values = train_df["rxn_str"].values

# Filter test_df based on values present in train_rxn_str_values
intersection_indices = test_df[test_df["rxn_str"].isin(train_rxn_str_values)].index

# Print the filtered rows
print(len(intersection_indices))
print(len(test_df))

30422
33930

In [4]:
test_df = test_df.drop(intersection_indices)
len(test_df)

3508

In [5]:
#save the new test_df as parquet
test_df.to_parquet("/Users/dsw46/Library/CloudStorage/OneDrive-UniversityofCambridge/Datasets/intersection_test_set.parquet")

# Find reactions/rows shared between the test sets

In [1]:
import pandas as pd

In [2]:
no_trust_test_path = "/Users/dsw46/Library/CloudStorage/OneDrive-UniversityofCambridge/Datasets/orderly_v5/orderly_no_trust_no_map_test.parquet"
with_trust_test_path = "/Users/dsw46/Library/CloudStorage/OneDrive-UniversityofCambridge/Datasets/orderly_v5/orderly_with_trust_no_map_test.parquet"
df1 = pd.read_parquet(no_trust_test_path)
df2 = pd.read_parquet(with_trust_test_path)

In [3]:
# Find indices where the rxn_str is the same

# Extract the values from the "rxn_str" column in df1 and df2
rxn_str_2 = df2["rxn_str"].values

# Filter df1 based on values present in df2 and vice versa
intersection_indices1 = df1[df1["rxn_str"].isin(rxn_str_2)].index

# Print the filtered rows
print(len(intersection_indices1))
print(len(df1))
print(len(df2))

corresponding_indices_in_df2 = []

# Loop through the filtered indices in df1
for idx in intersection_indices1:
    # Extract the 'rxn_str' value from df1
    rxn_str_value = df1.loc[idx, 'rxn_str']
    
    # Find the index in df2 where 'rxn_str' equals rxn_str_value
    corresponding_indices_in_df2.append(df2[df2['rxn_str'] == rxn_str_value].index[0])

275
33930
3373

In [4]:
intersection_indices1

Int64Index([ 71626, 154117, 149010,  60387,  64932, 119752,  25055, 227446,
            352683,   3653,
            ...
             19436,  91628,  12699,  12990, 206402,  79597, 235712,  70583,
            300095, 241611],
           dtype='int64', length=275)

In [5]:
corresponding_indices_in_df2[:5]

[6663, 15277, 14743, 5554, 6018]

In [10]:
df2.loc[corresponding_indices_in_df2]

,catalyst_000,date_of_experiment,extracted_from_file,grant_date,is_mapped,procedure_details,product_000,reactant_000,reactant_001,reagent_000,reagent_001,rxn_str,rxn_time,solvent_000,solvent_001,temperature,yield_000
6663,[Zn],NaT,ord_dataset-127eb5fdd5b4402e92b51d0b55a5dcb5,1997-01-01 00:01:00,True,"To a suspension of 1.52 g of trans-1,2,3,4-tet...",COc1cc2c(cc1OC)[C@@H](c1ccc(C)s1)[C@H](N)CC2,COc1cc2c(cc1OC)[C@@H](c1ccc(C)s1)[C@H]([N+](=O...,Cl,None,None,[CH3:1][O:2][C:3]1[CH:4]=[C:5]2[C:10](=[CH:11]...,0.50,CCO,None,25.0,98.9
15277,[Pd],NaT,ord_dataset-bf316bf78f4f45d4b275959c08104b7c,2007-01-01 00:06:00,True,To a solution of dibenzyl[7-(4-benzyloxy-3-iso...,COc1c(Oc2c(C)cc(N)c3c2CCC3)ccc(O)c1C(C)C,C=C(C)c1c(OCc2ccccc2)ccc(Oc2c(C)cc(N(Cc3ccccc3...,[H][H],None,None,C([N:8](CC1C=CC=CC=1)[C:9]1[CH:17]=[C:16]([CH3...,NaN,C1CCOC1,None,NaN,98.9
14743,[Pd],NaT,ord_dataset-844a22e1fcab44a5b59c5e2922b2855a,2007-01-01 00:01:00,True,A solution of {3-[3-(2-cyano-benzyl)-5-methyl-...,Cn1c(=O)c2c(nc(C3CCCC(N)C3)n2Cc2ccccc2C#N)c2cc...,Cn1c(=O)c2c(nc(C3CCCC(NC(=O)OCc4ccccc4)C3)n2Cc...,NULL,None,None,C(OC(=O)[NH:10][CH:11]1[CH2:16][CH2:15][CH2:14...,1.50,C1CCOC1,CCO,NaN,72.7
5554,CN(C)c1ccncc1,NaT,ord_dataset-bb4579c57ddc48c6a01fad97dacb6293,1994-01-01 00:08:00,True,"10 g of 2-amino-2',5-dichlorobenzophenone and ...",N#Cc1ccc(S(=O)(=O)Nc2ccc(Cl)cc2C(=O)c2ccccc2Cl...,N#Cc1ccc(S(=O)(=O)Cl)cc1,Nc1ccc(Cl)cc1C(=O)c1ccccc1Cl,None,None,[NH2:1][C:2]1[CH:16]=[CH:15][C:14]([Cl:17])=[C...,NaN,c1ccncc1,None,NaN,NaN
6018,[Pd],NaT,ord_dataset-fd1553bae35046c7a67523ff472cb5c3,1995-01-01 00:09:00,True,"To a solution of 1-(2-nitrophenyl)-2,2-dimethy...",CC(C)(C)C(=O)c1ccccc1N,CC(C)(C)C(=O)c1ccccc1[N+](=O)[O-],NULL,None,None,[N+:1]([C:4]1[CH:9]=[CH:8][CH:7]=[CH:6][C:5]=1...,0.33,CCO,Cl,NaN,70.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7504,[Ni],NaT,ord_dataset-7fed188163cf4ccca934ec71504c7f8a,1998-01-01 00:05:00,True,0.19 g (0.000537 mol) of 1-benzyl-piperidin-4-...,Nc1ccc(C(=O)OC2CCN(Cc3ccccc3)CC2)c(N)c1,Nc1cc([N+](=O)[O-])ccc1C(=O)OC1CCN(Cc2ccccc2)CC1,NULL,None,None,[NH2:1][C:2]1[CH:23]=[C:22]([N+:24]([O-])=O)[C...,NaN,CCO,None,NaN,88.7
23261,[Ni],NaT,ord_dataset-b195433d5c354ddfb6cde0d53c41910f,2012-01-01 00:04:00,True,"5-Methoxy-2,3-dihydroinden-1-one (1 g, 6.17 mm...",COc1ccc2c(c1)CCC2N,COc1ccc2c(c1)CCC2=NO,N,None,None,[CH3:1][O:2][C:3]1[CH:4]=[C:5]2[C:9](=[CH:10][...,8.00,CO,CO,25.0,45.0
6572,CN(C)c1ccncc1,NaT,ord_dataset-d0003732f14e4648a00d341275654590,1996-01-01 00:11:00,True,"A mixture of 2-amino-3-nitropyridine (1.39 g),...",CCCCCCCNC(=O)Nc1ncccc1[N+](=O)[O-],CCCCCCCN=C=O,Nc1ncccc1[N+](=O)[O-],None,None,[NH2:1][C:2]1[C:7]([N+:8]([O-:10])=[O:9])=[CH:...,NaN,Cc1ccccc1,None,NaN,36.8
29326,CN(C)c1ccncc1,NaT,ord_dataset-fd1fa959d6264608b0b7fcda16741bfd,2014-01-01 00:08:00,True,"A mixture of 6-fluoro-4,4-dimethyl-2-(3-pyrrol...",CC1(C)CC(c2cccc(N3CCCC3)c2)Nc2c(C(=O)NS(=O)(=O...,CC1(C)CC(c2cccc(N3CCCC3)c2)Nc2c(C(=O)O)cc(F)cc21,NS(=O)(=O)C1CC1,None,None,[F:1][C:2]1[CH:3]=[C:4]2[C:9](=[C:10]([C:12](O...,NaN,ClCCl,None,NaN,25.6
23828,[Pd],NaT,ord_dataset-0f9d2dbe929a45c3892ae75e81e99443,2012-01-01 00:06:00,True,235 mg (0.889 mmol) of the product from exampl...,CCOc1cc(N)ccc1N1CCCCC1=O,CCOc1cc([N+](=O)[O-])ccc1N1CCCCC1=O,[H][H],None,None,[CH2:1]([O:3][C:4]1[CH:9]=[C:8]([N+:10]([O-])=...,NaN,C1CCOC1,None,NaN,NaN

In [12]:
# Save the two dfs containing the intersections
df1.loc[intersection_indices1].to_parquet("/Users/dsw46/Library/CloudStorage/OneDrive-UniversityofCambridge/Datasets/orderly_v5/intersection/intersection_test_set_no_trust_no_map.parquet")
df2.loc[corresponding_indices_in_df2].to_parquet("/Users/dsw46/Library/CloudStorage/OneDrive-UniversityofCambridge/Datasets/orderly_v5/intersection/intersection_test_set_with_trust_no_map.parquet")